Repository honeycombio/libhoney-java, pull requests merged in 2021-08, with the labels that each got.

#62 Prepare v1.3.2 release
  CHANGELOG.md
  RELEASING.md
  libhoney/pom.xml
  pom.xml
Labels: version: bump patch, type: maintenance

#68 Add OSS lifecycle badge
  OSSMETADATA
  README.md
Labels: version: no bump

#71 Remove API Reference broken link from README
  README.md
Labels: type: documentation, status: review needed, version: no bump
