Repository honeycombio/libhoney-java, pull requests merged in 2022-08, with the labels that each got.

#151 maint: add Java 18 to CI matrix
  .circleci/config.yml
Labels: type: maintenance, version: no bump, merge at will

#153 Prepare v1.5.1 release
  CHANGELOG.md
  examples/pom.xml
  libhoney/pom.xml
  pom.xml
Labels: version: bump patch, type: maintenance

#154 Fix javadoc generation
  .circleci/config.yml
  pom.xml
Labels: type: bug, version: bump patch

#155 Prepare v1.5.2 release
  CHANGELOG.md
  examples/pom.xml
  libhoney/pom.xml
  pom.xml
Labels: version: bump patch, type: maintenance

#156 docs: add releasing step to update docs
  RELEASING.md
Labels: type: documentation, version: no bump, merge at will
